### ISSUE TITLE
was trying to run under ubuntu and got an error.

### ISSUE THREAD

**Issue by dasiopia** [ahmdrz/backup-direct-messages#1]
was trying to run under ubuntu and got an error.

error:

File "/mnt/c/DASI DISTRIB/insta-backup/instagram/instagram.py", line 5, in <module>
    import requests
ImportError: No module named requests

**Comment by ahmdrz** [comment]
Not related to this repo.
https://2.python-requests.org//en/v2.7.0/user/install/

try running pip install requests

**Comment by shardeex** [comment]
or try
`sudo apt-get install python-requests`
